apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: e2e-tests-parent-image-with-digest-only-cmnb
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: e2e-tests-parent-image-with-digest-only-cmnb
    app.kubernetes.io/part-of: test-app-886
  name: e2e-tests-parent-image-with-digest-only-cmnb
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: e2e-tests-parent-image-with-digest-only-cmnb
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: e2e-tests-parent-image-with-digest-only-cmnb
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/build-templates-e2e/test-app-886/e2e-tests-parent-image-with-digest-only-cmnb@sha256:fadd0420af0aa2df843e331902008c10ff54ccd269d7b1a475b2aad5ba60c17b
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8081
        resources: {}
status: {}
