apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: e2e-tests-parent-image-with-digest-only-cmnb
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: e2e-tests-parent-image-with-digest-only-cmnb
    app.kubernetes.io/part-of: test-app-886
  name: e2e-tests-parent-image-with-digest-only-cmnb
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: e2e-tests-parent-image-with-digest-only-cmnb
status:
  loadBalancer: {}
