apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: maven-hello-world-klps
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: maven-hello-world-klps
    app.kubernetes.io/part-of: test-app-886
  name: maven-hello-world-klps
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: maven-hello-world-klps
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: maven-hello-world-klps
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/build-templates-e2e/test-app-886/maven-hello-world-klps@sha256:5f729f41cd39d1d0d0c4ac59b9d48e7f0ee32067140555f68b18cd10b0199d78
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
