apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: pip-e2e-test-x6pt
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: pip-e2e-test-x6pt
    app.kubernetes.io/part-of: test-app-886
  name: pip-e2e-test-x6pt
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: pip-e2e-test
      app.kubernetes.io/instance: pip-e2e-test-x6pt
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: pip-e2e-test
        app.kubernetes.io/instance: pip-e2e-test-x6pt
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/build-templates-e2e/test-app-886/pip-e2e-test-x6pt@sha256:df8894dd83d6ba183bd27c4d0517c02f1978ce6a3908fcf99120644980fac782
        name: pip-e2e-test
        ports:
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
