apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: e2e-tests-parent-image-with-both-tag-digest-nenx
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: e2e-tests-parent-image-with-both-tag-digest-nenx
    app.kubernetes.io/part-of: test-app-886
  name: e2e-tests-parent-image-with-both-tag-digest-nenx
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: e2e-tests-parent-image-with-both-tag-digest-nenx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: e2e-tests-parent-image-with-both-tag-digest-nenx
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/build-templates-e2e/test-app-886/e2e-tests-parent-image-with-both-tag-digest-nenx@sha256:fbbe14480e67d7be6e6f46888c528afa999be646dc769e07c5fe4f6dd12a301a
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8081
        resources: {}
status: {}
