apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: retrodep-6u82
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: retrodep-6u82
    app.kubernetes.io/part-of: test-app-886
  name: retrodep-6u82
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: my-retrodep
      app.kubernetes.io/instance: retrodep-6u82
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: my-retrodep
        app.kubernetes.io/instance: retrodep-6u82
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/build-templates-e2e/test-app-886/retrodep-6u82@sha256:99a21f9c3a3ad317191994d0a87dcd31db443c9c884289f23d84ee3a778da8b5
        name: my-retrodep
        ports:
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
